server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8777/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}


spring:
  application:
    name: product-service
  datasource:
    url: jdbc:h2:tcp://localhost/~/product
    username: sa
    password: 123
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 20
      max-lifetime: 42000

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        database: h2
        format_sql: true
        default_batch_fetch_size: 1000
  h2:
    console:
      enabled: true

logging:
  config: classpath:logback-spring.xml
  level:
    org.hibernate.type: trace

springdoc:
  api-docs:
    enabled: true

product-app:
  rest:
    gateway:
      url: http://localhost:8888